import type { AdminListingReview } from '../types/admin';

export const mockAdminReviews: AdminListingReview[] = [
  {
    id: 'review-001',
    listingId: '2',
    title: 'Residential Plot in Lekki Phase 2',
    category: 'sale',
    location: 'Lekki Phase 2, Lagos',
    price: 45_000_000,
    thumbnail: 'https://images.unsplash.com/photo-1685266326195-76ad098af5d8?w=800&auto=format&fit=crop',
    listerName: 'Chioma Okafor',
    listerRole: 'agent',
    submittedAt: '2026-07-26T09:15:00Z',
    status: 'pending',
    documents: [
      {
        id: 'doc-001',
        type: 'Certificate of Occupancy',
        fileName: 'lekki-phase-2-c-of-o.pdf',
        fileSize: '2.4 MB',
        uploadedAt: '2026-07-26T09:10:00Z',
        status: 'pending',
        reference: 'LA/ET/2019/44821',
      },
      {
        id: 'doc-002',
        type: 'Survey Plan',
        fileName: 'registered-survey-plan.pdf',
        fileSize: '1.8 MB',
        uploadedAt: '2026-07-26T09:12:00Z',
        status: 'pending',
        reference: 'LS/ENG/33817',
      },
    ],
    flags: [],
  },
  {
    id: 'review-002',
    listingId: '3',
    title: 'Urgent Sale - Half Plot in Ikorodu',
    category: 'distress',
    location: 'Ikorodu, Lagos',
    price: 3_500_000,
    thumbnail: 'https://images.unsplash.com/photo-1684853693031-ab9e3f8c9d5e?w=800&auto=format&fit=crop',
    listerName: 'Tunde Balogun',
    listerRole: 'landowner',
    submittedAt: '2026-07-25T16:40:00Z',
    status: 'pending',
    documents: [
      {
        id: 'doc-003',
        type: 'Deed of Assignment',
        fileName: 'deed-of-assignment.pdf',
        fileSize: '3.1 MB',
        uploadedAt: '2026-07-25T16:32:00Z',
        status: 'pending',
      },
      {
        id: 'doc-004',
        type: 'Survey Plan',
        fileName: 'ikorodu-survey.jpg',
        fileSize: '4.6 MB',
        uploadedAt: '2026-07-25T16:35:00Z',
        status: 'pending',
        reference: 'IKD/231/2020',
      },
      {
        id: 'doc-005',
        type: 'Owner Identification',
        fileName: 'owner-id-redacted.pdf',
        fileSize: '820 KB',
        uploadedAt: '2026-07-25T16:38:00Z',
        status: 'pending',
      },
    ],
    flags: ['Price is 38% below comparable listings', 'Distress-sale reason requires confirmation'],
  },
  {
    id: 'review-003',
    listingId: '1',
    title: 'Fertile Farmland for Lease',
    category: 'lease',
    location: 'Otta, Ogun State',
    price: 500_000,
    thumbnail: 'https://images.unsplash.com/photo-1704230093402-c903d87735b4?w=800&auto=format&fit=crop',
    listerName: 'Adebayo Ogunlade',
    listerRole: 'agent',
    submittedAt: '2026-07-24T11:20:00Z',
    status: 'approved',
    documents: [
      {
        id: 'doc-006',
        type: 'Lease Authority',
        fileName: 'lease-authority.pdf',
        fileSize: '1.2 MB',
        uploadedAt: '2026-07-24T11:15:00Z',
        status: 'verified',
        reference: 'OG/LEASE/2026/112',
      },
    ],
    flags: [],
  },
];
