import type { Listing } from '../types/listing';

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Fertile Farmland for Lease',
    description:
      'Rich, fertile farmland ideal for crop cultivation. Well-irrigated with access to water supply. Perfect for commercial farming operations.',
    category: 'lease',
    status: 'available',
    price: 500000,
    priceUnit: 'per year',
    location: 'Otta, Ogun State',
    state: 'Ogun',
    lga: 'Ado-Odo/Ota',
    coordinates: { latitude: 6.6833, longitude: 3.2333 },
    size: 5,
    sizeUnit: 'acres',
    media: [
      { id: 'm1', uri: 'https://images.unsplash.com/photo-1704230093402-c903d87735b4?w=800&auto=format&fit=crop', type: 'image' },
      { id: 'm2', uri: 'https://images.unsplash.com/photo-1685266326473-5b99c3d08a7e?w=800&auto=format&fit=crop', type: 'image' },
    ],
    agent: {
      id: 'a1',
      name: 'Adebayo Ogunlade',
      avatar: 'https://i.pravatar.cc/150?img=11',
      phone: '+2348012345678',
      isVerified: true,
      totalListings: 12,
      rating: 4.8,
    },
    features: ['Irrigated', 'Road Access', 'Fenced', 'Water Supply'],
    leaseDuration: '1-5 years',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Residential Plot in Lekki Phase 2',
    description:
      'Prime residential land in Lekki Phase 2 with C of O. Excellent location close to major roads and amenities. Dry land, no swamp.',
    category: 'sale',
    status: 'available',
    price: 45000000,
    priceUnit: '',
    location: 'Lekki Phase 2, Lagos',
    state: 'Lagos',
    lga: 'Eti-Osa',
    coordinates: { latitude: 6.4281, longitude: 3.5413 },
    size: 1,
    sizeUnit: 'plots',
    media: [
      { id: 'm3', uri: 'https://images.unsplash.com/photo-1685266326195-76ad098af5d8?w=800&auto=format&fit=crop', type: 'image' },
      { id: 'm4', uri: 'https://images.unsplash.com/photo-1685266326184-0b570fe834fa?w=800&auto=format&fit=crop', type: 'image' },
    ],
    agent: {
      id: 'a2',
      name: 'Chioma Okafor',
      avatar: 'https://i.pravatar.cc/150?img=5',
      phone: '+2348087654321',
      isVerified: true,
      totalListings: 23,
      rating: 4.9,
    },
    features: ['C of O', 'Dry Land', 'Gated Estate', 'Close to Road'],
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-06-10T10:00:00Z',
  },
  {
    id: '3',
    title: 'Urgent Sale - Half Plot in Ikorodu',
    description:
      'Owner relocating abroad. Half plot of land in a developed area of Ikorodu. All documents available. Quick sale needed.',
    category: 'distress',
    status: 'available',
    price: 3500000,
    priceUnit: '',
    location: 'Ikorodu, Lagos',
    state: 'Lagos',
    lga: 'Ikorodu',
    coordinates: { latitude: 6.6194, longitude: 3.5105 },
    size: 0.5,
    sizeUnit: 'plots',
    media: [
      { id: 'm5', uri: 'https://images.unsplash.com/photo-1684853693031-ab9e3f8c9d5e?w=800&auto=format&fit=crop', type: 'image' },
    ],
    agent: {
      id: 'a3',
      name: 'Emeka Nwankwo',
      avatar: 'https://i.pravatar.cc/150?img=12',
      phone: '+2348098765432',
      isVerified: true,
      totalListings: 8,
      rating: 4.5,
    },
    features: ['Survey Plan', 'Receipt', 'Developed Area', 'Close to Market'],
    createdAt: '2026-06-18T10:00:00Z',
    updatedAt: '2026-06-19T10:00:00Z',
  },
  {
    id: '4',
    title: 'Poultry Farm for Lease',
    description:
      'Well-equipped poultry farm with capacity for 5000 birds. Includes feeders, drinkers, and housing structures. Water and electricity available.',
    category: 'lease',
    status: 'available',
    price: 1200000,
    priceUnit: 'per year',
    location: 'Ibadan, Oyo State',
    state: 'Oyo',
    lga: 'Akinyele',
    coordinates: { latitude: 7.3964, longitude: 3.9167 },
    size: 2,
    sizeUnit: 'acres',
    media: [
      { id: 'm6', uri: 'https://images.unsplash.com/photo-1577900190299-7316c32fe85f?w=800&auto=format&fit=crop', type: 'image' },
    ],
    agent: {
      id: 'a4',
      name: 'Folake Adeyemi',
      avatar: 'https://i.pravatar.cc/150?img=9',
      phone: '+2348076543210',
      isVerified: true,
      totalListings: 6,
      rating: 4.7,
    },
    features: ['Equipped', 'Water Supply', 'Electricity', 'Housing Structures'],
    leaseDuration: '1-3 years',
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-06-14T10:00:00Z',
  },
  {
    id: '5',
    title: 'Commercial Land in Abuja',
    description:
      'Prime commercial plot in Maitama district, Abuja. Ideal for office complex or mixed-use development. All approvals in place.',
    category: 'sale',
    status: 'available',
    price: 120000000,
    priceUnit: '',
    location: 'Maitama, Abuja',
    state: 'FCT',
    lga: 'Municipal',
    coordinates: { latitude: 9.0833, longitude: 7.4833 },
    size: 3,
    sizeUnit: 'plots',
    media: [
      { id: 'm7', uri: 'https://images.unsplash.com/photo-1704230093731-8dad84d386a9?w=800&auto=format&fit=crop', type: 'image' },
      { id: 'm8', uri: 'https://images.unsplash.com/photo-1537372023620-37161b1ad8ac?w=800&auto=format&fit=crop', type: 'image' },
    ],
    agent: {
      id: 'a5',
      name: 'Ibrahim Yusuf',
      avatar: 'https://i.pravatar.cc/150?img=15',
      phone: '+2348065432109',
      isVerified: true,
      totalListings: 31,
      rating: 4.9,
    },
    features: ['C of O', 'Approved Plan', 'Corner Piece', 'Main Road'],
    createdAt: '2026-05-15T10:00:00Z',
    updatedAt: '2026-06-05T10:00:00Z',
  },
  {
    id: '6',
    title: 'Fish Pond for Lease - Epe',
    description:
      'Operational fish pond with 10 concrete ponds. Borehole, generator house, and store room available. Suitable for catfish or tilapia farming.',
    category: 'lease',
    status: 'available',
    price: 800000,
    priceUnit: 'per year',
    location: 'Epe, Lagos',
    state: 'Lagos',
    lga: 'Epe',
    coordinates: { latitude: 6.5833, longitude: 3.9833 },
    size: 1,
    sizeUnit: 'acres',
    media: [
      { id: 'm9', uri: 'https://images.unsplash.com/photo-1685266326473-5b99c3d08a7e?w=800&auto=format&fit=crop', type: 'image' },
    ],
    agent: {
      id: 'a6',
      name: 'Kemi Bakare',
      avatar: 'https://i.pravatar.cc/150?img=20',
      phone: '+2348054321098',
      isVerified: false,
      totalListings: 3,
      rating: 4.2,
    },
    features: ['Concrete Ponds', 'Borehole', 'Generator House', 'Store Room'],
    leaseDuration: '1-2 years',
    createdAt: '2026-06-12T10:00:00Z',
    updatedAt: '2026-06-16T10:00:00Z',
  },
];
